security:
    encoders:
        Instacount\InstacountBundle\Entity\User: plaintext
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: InstacountInstacountBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                always_use_default_target_path: true
                default_target_path: /admin
            logout:
                path:   /logout
                target: /  
                invalidate_session: false          

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
