security:
    encoders:
        Instacount\InstacountBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: InstacountInstacountBundle:User }

    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic: ~
            logout: ~
                 

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }