security:
    encoders:
        Instacount\InstacountBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: InstacountInstacountBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout:
                path:   /logout
                target: /            

    access_control:
        - { path: ^/admin, roles: ROLE_USER }
