InstacountInstacountBundle_homepage:
    pattern:  /
    defaults: { _controller: InstacountInstacountBundle:Page:index }
    requirements:
        _method:  GET

InstacountInstacountBundle_counter_show:
    pattern:  /counter/{id}
    defaults: { _controller: InstacountInstacountBundle:Counter:show }
    requirements:
        _method:  GET
        id: \d+

InstacountInstacountBundle_counter_last:
    pattern:  /counter/last
    defaults: { _controller: InstacountInstacountBundle:Counter:showLastCount }
    requirements:
        _method:  POST

InstacountInstacountBundle_counter_index:
    pattern:  /counter
    defaults: { _controller: InstacountInstacountBundle:Counter:index }
    requirements:
        _method:  GET
        id: \d+

InstacountInstacountBundle_counter_create:
    pattern:  /counter/create
    defaults: { _controller: InstacountInstacountBundle:Counter:create }
    requirements:
        _method:  POST

InstacountInstacountBundle_campaign_json:
    pattern:  /campaign/{campaign_id}/json
    defaults: { _controller: InstacountInstacountBundle:Counter:json }
    requirements:
        _method:  GET
        id: \d+

InstacountInstacountBundle_campaign_json_map:
    pattern:  /campaign/{campaign_id}/json_map
    defaults: { _controller: InstacountInstacountBundle:Counter:jsonMap }
    requirements:
        _method:  GET
        id: \d+
       

InstacountInstacountBundle_admin:
    pattern:  /admin
    defaults: { _controller: InstacountInstacountBundle:Campaign:index }
    requirements:
        _method:  GET


InstacountInstacountBundle_campaign:
    pattern:  /admin/campaign
    defaults: { _controller: InstacountInstacountBundle:Campaign:index }
    requirements:
        _method:  GET

InstacountInstacountBundle_campaign_show:
    pattern:  /admin/campaign/{id}
    defaults: { _controller: InstacountInstacountBundle:Campaign:show }
    requirements:
        _method:  GET
        id: \d+

InstacountInstacountBundle_campaign_new:
    pattern:  /admin/campaign/new
    defaults: { _controller: InstacountInstacountBundle:Campaign:new }
    requirements:
        _method:  GET

InstacountInstacountBundle_campaign_create:
    pattern:  /admin/campaign/create
    defaults: { _controller: InstacountInstacountBundle:Campaign:create }
    requirements:
        _method:  POST

InstacountInstacountBundle_campaign_update:
    pattern:  /admin/campaign/{id}/update
    defaults: { _controller: InstacountInstacountBundle:Campaign:update }
    requirements:
        _method:  POST

InstacountInstacountBundle_campaign_edit:
    pattern:  /admin/campaign/{id}/edit
    defaults: { _controller: InstacountInstacountBundle:Campaign:edit }
    requirements:
        _method:  GET

InstacountInstacountBundle_campaign_delete:
    pattern:  /admin/campaign/{id}/delete
    defaults: { _controller: InstacountInstacountBundle:Campaign:delete }
    requirements:
        _method:  GET

InstacountInstacountBundle_user:
    pattern:  /admin/user
    defaults: { _controller: InstacountInstacountBundle:User:index }
    requirements:
        _method:  GET

InstacountInstacountBundle_user_show:
    pattern:  /admin/user/{id}
    defaults: { _controller: InstacountInstacountBundle:User:show }
    requirements:
        _method:  GET
        id: \d+

InstacountInstacountBundle_user_new:
    pattern:  /admin/user/new
    defaults: { _controller: InstacountInstacountBundle:User:new }
    requirements:
        _method:  GET

InstacountInstacountBundle_user_create:
    pattern:  /admin/user/create
    defaults: { _controller: InstacountInstacountBundle:User:create }
    requirements:
        _method:  POST 

InstacountInstacountBundle_user_create_first:
    pattern:  /user/create_first
    defaults: { _controller: InstacountInstacountBundle:User:create_first }
    requirements:
        _method:  POST        

InstacountInstacountBundle_user_update:
    pattern:  /admin/user/{id}/update
    defaults: { _controller: InstacountInstacountBundle:User:update }
    requirements:
        _method:  POST        

InstacountInstacountBundle_user_edit:
    pattern:  /admin/user/{id}/edit
    defaults: { _controller: InstacountInstacountBundle:User:edit }
    requirements:
        _method:  GET

InstacountInstacountBundle_user_delete:
    pattern:  /admin/user/{id}/delete
    defaults: { _controller: InstacountInstacountBundle:User:delete }
    requirements:
        _method:  GET


      




