parameters:
#    instacount_instacount.example.class: Instacount\InstacountBundle\Example

services:
#    instacount_instacount.example:
#        class: %instacount_instacount.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
